const MAX_SELECTED_MOVIES = 20;
const SOCIAL_ICON_SIZE = 32;
const CLOSE_ALERT_DELAY = 2000;
const COUNT_OF_PAGES = 500;
const LOCALES = {
  ENGLISH: 'en-us',
  UKRAINIAN: 'uk'
}

export { 
  MAX_SELECTED_MOVIES, 
  SOCIAL_ICON_SIZE,
  CLOSE_ALERT_DELAY,
  COUNT_OF_PAGES,
  LOCALES
}